### ISSUE TITLE
 Introduce `coffee disable` and `coffee enable` Commands

### ISSUE THREAD

**Issue by tareknaser** [coffee-tools/coffee#102]
# Background
Currently, `coffee` provides functionality for managing plugins within the Core Lightning. Users can easily install, configure, and manage plugins using `coffee`'s intuitive commands. 
However, there are scenarios where users may need to disable all plugins installed by `coffee`. This can be necessary for a variety of reasons, such as debugging or troubleshooting issues related to specific plugins or temporarily reverting to a clean Core Lightning environment.

# Goal
The goal of this enhancement is to introduce a new `coffee` command that allows users to disable all plugins previously installed by `coffee`. This feature will provide users with greater flexibility and control over their Core Lightning setup. By running this command, users can effectively "turn off" all plugins, ensuring a clean and predictable Core Lightning environment.

# Example Usage
```shell
# To disable all plugins installed by coffee
coffee disable

# To enable all plugins installed by coffee
coffee enable
```

# Room for Improvement
While the initial implementation focuses on enabling or disabling all plugins at once, there is room for improvement by allowing users to disable individual plugins. To achieve this, the enhancement could introduce the ability to disable a specific plugin using a command like:
```shell
coffee disable <plugin-name>
```

**Comment by vincenzopalazzo** [comment]
@Harshit933 want to play a little bit with rust, so the goal of this issue is to add the new command that is coffee --network testnet disable <name_plugin>, and you should do two things, stop the plugin from core lightning, and if the plugin is inside the coffee configuration remove the plugin from this configuration

**Comment by vincenzopalazzo** [comment]
I think this needs also to implement the enable command to add just the plugin without installing it. But I do not know how it plays with our current architecture
