### ISSUE TITLE
coffee storage is broken with the json file

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#117]
We are currently experiencing issues with our coffee system. All the information is stored 
in a JSON file, but due to changes in the coffee structure, we are no longer able to load the JSON file. 

We need to switch to using a database instead. We are considering using either a 
SQL database or a NoSQL database with its own format. While I'm personally 
inclined towards a NoSQL database, I'm open to discussing and 
considering other options.

**Comment by tareknaser360** [comment]
solved with #162
