### ISSUE TITLE
coffee: Does not take into account that the remote inside the directory already exists

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#122]
The PR https://github.com/coffee-tools/coffee/pull/115 does not include the case where we try to remove the `.coffee/storage.json` file with a remote already added, leaving the `repository` directory in a dirty state.

Therefore, during the sanity check, we should verify if the list of repositories contains any repositories that exist as directories but do not exist inside the storage.

```
     Running `target/debug/coffee remote add folgore-git 'https://github.com/coffee-tools/folgore.git'`
[2023-05-02T13:09:21Z ERROR coffee_lib::errors] ERROR #1: '/home/vincent/.coffee/repositories/folgore-git' exists and is not an empty directory
✗ Fetch remote from https://github.com/coffee-tools/folgore.git error: Error while add remote: code: 1, msg: '/home/vincent/.coffee/repositories/folgore-git' exists and is not an empty directory
Error: CoffeeError { code: 1, msg: "'/home/vincent/.coffee/repositories/folgore-git' exists and is not an empty directory" }

```

**Comment by tareknaser360** [comment]
So we should modify the `remote_sync` function in #115 to also check for folders/files inside .repositories folder and if so, returns an error
right?

**Comment by vincenzopalazzo** [comment]
@tareknaser360 now we can start to think about this by looking inside the nurse recovery stategies

**Comment by tareknaser** [comment]
This issue seems outdated. Since then, we've made several changes:
- We switched coffee's storage to NoSQL
- Implemented `coffee nurse` using a strategy design

I think this issue is no longer relevant. Could you confirm, @vincenzopalazzo?

**Comment by vincenzopalazzo** [comment]
I trust you :)
