### ISSUE TITLE
Nurse Command Recovery Strategy Cases and Handlers

### ISSUE THREAD

**Issue by tareknaser** [coffee-tools/coffee#128]
|**Case**|**Handler**|
|---|---|
|1. A `git` repository exists in `coffee` configuration but absent from local storage|- &#9744; Attempt to clone the repository using the `git` HEAD reference stored in the configuration.<br/>- &#9744; If the cloning process fails, remove the repository entry from the configuration.|
|2. A repository is present in local storage (`./coffee/repositories`) but is not documented in `coffee` configuration|- &#9744; Make an attempt to index the repository, verifying if it is a `git` repository, and subsequently add it to the `coffee` configuration.<br/>- &#9744; If indexing fails, the repository will be removed from the `repositories` folder.|
|3. A `git` repository is found to be corrupt, typically due to a missing file or other issues|- &#9744; Recover using the `git` HEAD.|

**Note: Before proceeding with any of these actions, we have to ensure that the user has confirmed**

**Comment by vincenzopalazzo** [comment]
We should also try to recover the state of the storage is the git repository has no changes

**Comment by vincenzopalazzo** [comment]
Ok I noted that if the `.coffee/repository` do not exist the call `self.remote_sync` fails.

So this is wrong for some commands like add remote, `self.remote_sync` fails when there is no repository directory
we will be never able to add a new remote.

This feature looks untested. Are you testing your PR on your system?

**Comment by tareknaser360** [comment]
Yes I think I missed this corner case
I tested the function locally but this issue only happens when the user sets up coffee the first time

**Comment by vincenzopalazzo** [comment]
>I tested the function locally but this issue only happens when the user sets up coffee the first time

or you use the --data-dir, so the test that we need to run each time is create a new directory and make sure that we do not introduce regression
