### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by dcrystalj** [coffee-tools/coffee#138]
When I read the following statement
```
The idea that we have for Coffee is to be the de facto tool to install and build a plugin in Core Lightning
```
I would expect to have plugins work out of the box but looks like dependencies are not installed but at least for official repo should be ?

Example:

## Fresh install
```
$ coffe remote install backup
...
$ coffee list
● Plugin installed
╭──────────────────────────────────────────────────────────────────────────────────────╮
│ ●   Language   Name     Exec path                                                    │
├──────────────────────────────────────────────────────────────────────────────────────┤
│ ●   python     backup   /home/bitcoin/.coffee/repositories/official/backup/backup.py │
╰──────────────────────────────────────────────────────────────────────────────────────╯
```

## Run
```
$ lightningd --network=bitcoin --log-level=debug
Traceback (most recent call last):
  File "/home/bitcoin/.coffee/repositories/official/backup/backup.py", line 2, in <module>
    from pyln.client import Plugin
ModuleNotFoundError: No module named 'pyln'
```

## Expectation
I had to manually run `pip3 install pyln-client` but would expect to coffee handle this for me.

I would also somewhat expect to not need to go to backup dir and need to run.
```
./backup-cli init --lightning-dir ~/.lightning/bitcoin file:///mypath/lightning.bkp
```

**Comment by vincenzopalazzo** [comment]
Mh you are right, but you paste the wrong command. `coffee remote install backup` will never work

Assuming that you add the remote in the correct way (check with `coffee remote list`)

Can you post the result of the following command?

```
coffee --network <bitcoin network> install backup -v
```

If I ran the current master I get 

```
➜  coffee git:(master) coffee --network testnet install backup -v                             

Usage:   
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --output
✓ Plugin backup Compiled and Installed
➜  coffee git:(master) 
```

and this looks like a bug

**Comment by vincenzopalazzo** [comment]
Could you please test https://github.com/coffee-tools/coffee/pull/139 ?

**Comment by dcrystalj** [comment]
I get same output  ```
$ coffee --network testnet install backup -v

Usage:
  pip3 install [options] <requirement specifier> [package-index-options] ...
  pip3 install [options] -r <requirements file> [package-index-options] ...
  pip3 install [options] [-e] <vcs project url> ...
  pip3 install [options] [-e] <local project path> ...
  pip3 install [options] <archive url/path> ...

no such option: --output
✓ Plugin backup Compiled and Installed
```
But I installed pyln-client already by myself.

🙇 for quick response

I can test this tomorrow.

**Comment by vincenzopalazzo** [comment]
Yeah I introduced the bug while I was refactoring the code :/

So the PR will fix this for me, let me know if this will be fixed also for you :)

**Comment by dcrystalj** [comment]
I can confirm that #139  fixes issue. 🎉 It also fixes broken `coffee show backup` command 👍 
my test procedure:
```sh
pip uninstall pyln-client
sudo rm -rf /home/bitcoin/.coffee
git fetch --all
git checkout macros/poetry_dep
make install
coffee setup /home/bitcoin/.coffee
coffee remote add official https://github.com/lightningd/plugins.git
coffee install backup
```

regarding 
```
Mh this looks like more difficult to do currently, there are too many parameters that depends from the user, but I can think a little bit on how to do it```

What if this would be after install procedure? You get prompt to enter "path" (/mypath/lightning.bkp) and than it runs the command for you?

**Comment by vincenzopalazzo** [comment]
>What if this would be after install procedure? You get prompt to enter "path" (/mypath/lightning.bkp) and than it runs the command for you?

Yeah maybe we can add a way with the coffee manifest https://coffee-docs.netlify.app/support-coffee.html to support this case; there are several use cases to get the input from the user, like plugin configuration.

Maybe your request can be included inside the https://github.com/coffee-tools/coffee/pull/101

I will open the discussion on github to track this and when I have a good idea we can implement the solution, but in any case I love your suggestion.

Thanks for taking the time to test my PR :) and test coffee

**Comment by vincenzopalazzo** [comment]
Done https://github.com/coffee-tools/coffee/discussions/140
