### ISSUE TITLE
bad url inside the plugin struct in some cases

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#141]
While testing the https://github.com/coffee-tools/coffee/pull/134 we should find the cause and normalize the URL

I noted that the URL does not look right

```json 
{
  "plugins": [
    {
      "conf": null,
      "exec_path": "/tmp//.coffee/repositories/official/backup/backup.py",
      "lang": "PyPoetry",
      "name": "backup",
      "root_path": "/tmp//.coffee/repositories/official/backup"
    },
    {
      "conf": null,
      "exec_path": "/tmp//.coffee/repositories/official/summary/summary.py",
      "lang": "PyPip",
      "name": "summary",
      "root_path": "/tmp//.coffee/repositories/official/summary"
    }
  ]
}

```

there is an extra `/` in `"exec_path": "/tmp//.coffee/repositories/official/backup/backup.py"`

**Comment by vincenzopalazzo** [comment]
This can be solved by https://github.com/coffee-tools/coffee/pull/142#pullrequestreview-1451027324 but need to be tested in various test cases

**Comment by tareknaser360** [comment]
Is this solved?

**Comment by vincenzopalazzo** [comment]
I do no know :) we should write a test for confirm
