### ISSUE TITLE
create a contribute file

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#204]
To participate in the October fest we should create a CONTRIBUTING.md

**Comment by Arcturus22** [comment]
Please assign me this issue @vincenzopalazzo

**Comment by vincenzopalazzo** [comment]
@tareknaser is working on it sorry! there are other issue where you can work

**Comment by tareknaser** [comment]
we already have [a contributing file](https://github.com/coffee-tools/coffee/blob/master/docs/docs-book/src/contributing-to-coffee.md) that I can move to the project home directory. 

should I just duplicate it or just remove it from the docs?

**Comment by vincenzopalazzo** [comment]
> should I just duplicate it or just remove it from the docs?

Yes
