### ISSUE TITLE
remote: add a new command to inspect the plugins inside the remote

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#261]
Currently, it is really hard to see the plugins inside a remote, so I will propose a new command called `inspect` that works like `coffee remote --plugins folgore-git list`

So currently to see the plugins inside a directory you need to do

```
➜  ~ coffee remote --plugins folgore-git list
● Plugins installed
```

but IMHO this should be a little bit better, an example:

```
➜  ~ coffee remote inspect folgore-git
● Plugins installed
```

`inspect` is more intuitive

What do you think @tareknaser

**Comment by tareknaser** [comment]
I agree. `inspect` is more straightforward
