### ISSUE TITLE
Network Validation in Command Line Inputs

### ISSUE THREAD

**Issue by tareknaser** [coffee-tools/coffee#270]
## Description 
Currently, `coffee` does not validate if the network supplied in the command line is valid.
Running `coffee -n remote list` by mistake creates `/Users/tareknasser/.coffee/remote`

**Comment by vincenzopalazzo** [comment]
I did too :) we should validate the network is one of the cln supported one

Shoulds be really trivial

**Comment by vincenzopalazzo** [comment]
@Anyitechs there is no need to ask or advertize that you are working on some issue, just open a PR

**Comment by Anyitechs** [comment]
> @Anyitechs there is no need to ask or advertize that you are working on some issue, just open a PR

Ok. Thank you.

**Comment by Anyitechs** [comment]
Hi @vincenzopalazzo, I opened a draft PR [here](https://github.com/coffee-tools/coffee/pull/274).

Let me know your thoughts.

cc: @tareknaser

**Comment by vincenzopalazzo** [comment]
Marking the commit as out of scope, please @Anyitechs do not use the github issue as a direct chat with the maintainer, if maintainer want to be reached they have an email in the github profile.
