### ISSUE TITLE
How to uninstall coffee?

### ISSUE THREAD

**Issue by urza** [coffee-tools/coffee#277]
There are no instructions in docs how to uninstall coffee.

Alternatively also how to disable coffee temporarily.

**Comment by vincenzopalazzo** [comment]
>There are no instructions in docs how to uninstall coffee.

I do not think this is true

- Removing a plugin https://coffee-docs.netlify.app/using-coffee#removing-a-plugin
- Disabling a plugin https://coffee-docs.netlify.app/using-coffee#disabling-a-plugin
- Remove a repository https://coffee-docs.netlify.app/using-coffee#add-a-plugin-repository

Then if you do not like the import inside the cln config you can remove the `import <path to the config file>`

Let me know if this solve your problem, otherwise feel free to reopen the issue

**Comment by urza** [comment]
Thanks, but I meant how do I uninstall (or disable) the whole coffee manager itself?

**Comment by vincenzopalazzo** [comment]
>Thanks, but I meant how do I uninstall (or disable) the whole coffee manager itself?

I do not understand what you mean, but maybe with the following

>Then if you do not like the import inside the cln config you can remove the import <path to the config file> from your lightning configuration file

**Comment by daywalker90** [comment]
> Thanks, but I meant how do I uninstall (or disable) the whole coffee manager itself?

really depends on what you mean here. The coffee binary?
```
rm "$(which coffee)"
```
If you mean all the configs it generated that would affect your lightning node then do what @vincenzopalazzo wrote and remove the config line.

**Comment by urza** [comment]
I probably just imagined that coffee is something that it is not. I expected the install process created some kind of service running that hooked into CLN.. but that doesn't seem to be the case?

Anyway so in general when I followed this https://coffee-docs.netlify.app/install-coffee and this https://coffee-docs.netlify.app/using-coffee

And I want to go back to how CLN was working before, I just remove the "include" in the lightningd config and remove any plugins from the config that are manged by coffee and that's it?

**Comment by vincenzopalazzo** [comment]
>I probably just imagined that coffee is something that it is not. I expected the install process created some kind of service running that hooked into CLN.. but that doesn't seem to be the case?

No there is no deamon running

>And I want to go back to how CLN was working before, I just remove the "include" in the lightningd config and remove any plugins from the config that are manged by coffee and that's it?

Correct
