### ISSUE TITLE
cmd: add the possibility to unlinks the core lightning form coffee

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#278]
We have a `coffee setup` command, but we do not have and unlink command, so we should add it to make it easy.

`coffee unlink <cln root path>`, and then maybe we can rename the `coffee setup` to `coffee link`?

What do you think @tareknaser ?

**Comment by tareknaser** [comment]
Maybe we can have:
- `coffee setup` and `coffee teardown`  
or
- `coffee activate` and `coffee deactivate`

**Comment by tareknaser** [comment]
I gave this a try, but it looks like we need to wait for https://github.com/laanwj/cln4rust/pull/131 before testing. Here is the commit: https://github.com/coffee-tools/coffee/commit/862a9ebfa63ab979e97835a44bf73f3bb5e5df10

**Comment by vincenzopalazzo** [comment]
No better, link and unlink

You are not activating anything, but you are linking the core lightning configuration to the coffee configuration.

In Linux terms, this is a link operation https://linuxize.com/post/how-to-create-symbolic-links-in-linux-using-the-ln-command/
