### ISSUE TITLE
Support `remove` command to remove a plugin that is currently installed by coffe

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#41]
# Background

To run Coffe you are run the following command `cargo run -- --help` and you can run the following command to setup coffee for your core lightning node

```
cargo run -- setup <core lightning root path>
cargo run -- remote add lightningd https://github.com/lightningd/plugins.git
cargo run -- install <plugin_name>
```

Currently, there is no way to remove the plugin that we just installed, so this task required you to implement the remove command.

# Goal

Be able to run the following command 
```
cargo run -- remove <name_plugin>
```

**Comment by royalpinto007** [comment]
Hey @vincenzopalazzo,
Please assign this issue to me, and I will start working on it right away.

**Comment by tareknaser360** [comment]
I was planning to work on this issue. Is there any pre-SoB issues I can work on?

**Comment by royalpinto007** [comment]
As I believe changes are required in three files, I will be working on this issue in steps by adding commits to each file one by one.

**Comment by royalpinto007** [comment]
https://github.com/coffee-tools/coffee/pull/48

This improves the functionality of the CoffeeCommand::Remove method by allowing the removal of specific plugins from the coffee instance. This change also improves the overall maintainability of the code by replacing the placeholder statement with a functional implementation.

I will do the changes in the remaining files too.

**Comment by vasvigarg** [comment]
is the issue resolved yet or can i work on it?

**Comment by vincenzopalazzo** [comment]
@vasvigarg you can!

**Comment by vasvigarg** [comment]
pls assign

**Comment by vincenzopalazzo** [comment]
as you can see there is no need to assign!
