### ISSUE TITLE
Support  the verbose output while running the install and upgrade command

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#44]
# Background

To run Coffe you are run the following command `cargo run -- --help` and you can run the following command to setup coffee for your core lightning node

```
cargo run -- setup <path of the core lightning file>
cargo run -- remote add lightningd https://github.com/lightningd/plugins.git
cargo run -- install <plugin_name>
```

Currently when you are running `install` you see in the terminal the install output like the python output, this is not good if we want to implement a Terminal UI https://github.com/coffee-tools/coffee/issues/16

The goal of this task is to hide the output of the install command and show the output caused by the python command just when the user specifies it.

# Goal

Be able to run the following command 

```
cargo run -- install <plugin_name> --verbose
```

**Comment by Harshit933** [comment]
Hey I would like to work on this issue
