### ISSUE TITLE
Inferer the plugin information from the configuration file if exist

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#49]
# Background

To run Coffe you are run the following command `cargo run -- --help` and you can run the following command to setup coffee for your core lightning node

```
cargo run -- setup <path of the core lightning file>
cargo run -- remote add lightningd https://github.com/lightningd/plugins.git
cargo run -- install <plugin_name>
```

Currently, there is a FIXME inside the code https://github.com/coffee-tools/coffee/blob/master/coffee_github/src/repository.rs#L104-L114 that suggest searching before if the plugin has the coffee configuration file, and then guess the language by iterating on each file.

# Goal

So the goal is to refactor the code to get the information from the configuration file, where an example of conf file looks like the following one https://github.com/coffee-tools/coffee/blob/master/coffee.yml

In order to achieve this, you should put create a configuration file inside on of the plugin that are in the repository https://github.com/lightningd/plugins.git and test if your solution wortks

**Comment by tareknaser360** [comment]
Can you assign this to me?
