### ISSUE TITLE
Improving how we store the installed plugins information

### ISSUE THREAD

**Issue by tareknaser360** [coffee-tools/coffee#53]
## Current situation
We currently store only the path to the installed plugins in `plugins_path` as a string. This is not enough to make the command line UI good.
Information to be added:
- [ ] the name of the plugin
- [ ] the plugin language
- [ ] the plugin version 

## Suggested solution
There are 2 options whenever we try to install a new plugin:
1- The plugin has a coffee configuration yaml file
- In this case all the information can be extracted easily from the yaml file

2- The plugin doesn't have a coffee configuration yaml file
- Here we can extract the name by using the `get_plugin_info_from_path` as it returns `path_to_plugin`, `plugin_name` 
- The plugin language can be guessed by iterating over the files
- I can't think of an easy way to know the version of the plugin in that situation

Also, what kind of data structure should we use to store that information?
A separate string vector for every attribute of the plugin seems like a very bad solution

**Comment by tareknaser360** [comment]
Can you assign me this issue?

**Comment by tareknaser360** [comment]
The solution proposed in #55 doesn't solve the issue for the version of the plugin.
In case the plugin has a coffee configuration file, we can easily get the version and maybe add that to the plugin struct.
But I can't think of a way to find the version of the plugin if there is no coffee configuration file.
A sample plugin file tree would look something like this:
```
helpme/
├── Makefile
├── README.md
├── helpme.py
├── requirements-dev.txt
├── requirements.txt
└── test_helpme.py
```
Is there a way to find the version here?

**Comment by vincenzopalazzo** [comment]
> But I can't think of a way to find the version of the plugin if there is no coffee configuration file.

because there is no way!

**Comment by tareknaser360** [comment]
I can also implement a new field `PluginVer` for the `Plugin` struct and set the default value to be Unknown.
But then we will have information about the plugin version for only a subset of the plugins so I am not sure this is what we want.

**Comment by vincenzopalazzo** [comment]
the version is inside the configuration already
