### ISSUE TITLE
allow to create a empty core lightning config when it is missed inside the `./lightning/<network>/`

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#57]
# Background

To run Coffe you are run the following command `cargo run -- --help` and you can run the following command to setup coffee for your core lightning node

```
cargo run -- setup <path of the core lightning file>
cargo run -- remote add lightningd https://github.com/lightningd/plugins.git
cargo run -- install <plugin_name>
```

Currently, if the user does have not the config file, the user should create an empty file, this could be done by coffee and it is already supported by the design of our configuration parser.

# Goal

the following command should create the empty configuration file if it is missed

```
cargo run -- setup <path of the core lightning file>
```

**Comment by tareknaser360** [comment]
Can I get assigned this?
