### ISSUE TITLE
design the interface to allow web application or any of this to run coffe as server

### ISSUE THREAD

**Issue by vincenzopalazzo** [coffee-tools/coffee#59]
# Background

To run Coffe you are run the following command `cargo run -- --help` and you can run the following command to setup coffee for your core lightning node

```
cargo run -- setup <core lightning root path>
cargo run -- remote add lightningd https://github.com/lightningd/plugins.git
cargo run -- install <plugin_name>
```

but by looking inside the core lightning https://github.com/ElementsProject/lightning/issues/5833 there is a need to use 
core lightning with some kind of server or just move the UI as a plugin.

In this case, I would like to ship both and then deprecate the one that the people are not using (I assume the plugin one, because to me looks a little bit confusing at the moment)

## Pre-Goal

This is an additional SoB that required downgrading one of the previous ones, and for this one, the requirements are designed and email me to discuss the proposal for https://github.com/coffee-tools/coffee/issues/42 and then implement it as pre-SoB

While you are implementing the pre-SoB you need also to think about how the proposal of this project looks like

# Goal

The goal is to implement a web server crate `coffe_httpd` that supports the following feature:

- HTTP request to run commands like `install`
- Some ws event stream to receive real-time updates while the installation is running (this allow also async updates from the UI)) on a possible protocol that we can try to use is graphql that has a standard for it

**Comment by tareknaser360** [comment]
Implemented over some PRs. Latest of which is #175 
Only thing missing is the authentication method but we have a separate issue for that #179

**Comment by vincenzopalazzo** [comment]
This is completed by @tareknaser this summar
