### ISSUE TITLE
[feat]: Support dynamic plugins for systems that don't allow direct changes to the CLN config file

### ISSUE THREAD

**Issue by chrisguida** [coffee-tools/coffee#66]
On embassyOS, our current config system does not respect changes made to the CLN config file because it rewrites this file on every restart from user input from our frontend. So, in order for us to incorporate coffee, either coffee needs to allow dynamic installation/starting of plugins (and I need to dynamically launch the plugins discovered in the plugins dir) or I need to rewrite our config set action to incorporate updates *both* direct updates to the CLN config and updates from the config element in the UI.

The latter of these is probably preferable, but will be a total rewrite of CLN's config generation code. If dynamic plugin support can easily be added to coffee, then we can incorporate coffee sooner :)

**Comment by vincenzopalazzo** [comment]
This was already on the queue https://github.com/coffee-tools/coffee/issues/36

But I think also rewrite your config manager is an option, not always we can use the dynamic plugin.

In addition, if you need a helper to generate core lightning config with rust I made a package https://github.com/laanwj/cln4rust/tree/master/conf

**Comment by chrisguida** [comment]
Cool, thanks! I think I probably need to write it in Typescript, since that's what our config system uses, but maybe I can make a rust binary callable from TS that uses this lib

**Comment by vincenzopalazzo** [comment]
let me know if you want any help from rust side, the binding looks promising
